# Generated by Django 6.0.3 on 2026-04-01 14:58

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Videos',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('file', models.FileField(upload_to='videos/')),
                ('date', models.DateField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Видео продукта',
                'verbose_name_plural': 'Видео продуктов',
            },
        ),
    ]
