# Generated by Django 6.0.3 on 2026-04-03 14:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('videos', '0002_videos_title_en_videos_title_ru_videos_title_tk'),
    ]

    operations = [
        migrations.AddField(
            model_name='videos',
            name='poster',
            field=models.ImageField(blank=True, null=True, upload_to='images/video-poster/'),
        ),
    ]
