# Generated by Django 6.0.3 on 2026-04-01 14:58

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('news', '0001_initial'),
        ('products', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='news',
            name='products',
            field=models.ManyToManyField(blank=True, related_name='news_list', to='products.products'),
        ),
    ]
