# Generated by Django 6.0.3 on 2026-04-03 14:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0004_category_name_en_category_name_ru_category_name_tk_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='news',
            name='poster',
            field=models.ImageField(blank=True, null=True, upload_to='news/posters/'),
        ),
    ]
