# Generated by Django 6.0.3 on 2026-04-18 18:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('applications', '0001_initial'),
        ('news', '0005_news_poster'),
    ]

    operations = [
        migrations.AddField(
            model_name='news',
            name='applications',
            field=models.ManyToManyField(blank=True, to='applications.application'),
        ),
    ]
