# Generated by Django 6.0.3 on 2026-04-18 18:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0006_news_applications'),
        ('site_applications', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='news',
            name='applications',
            field=models.ManyToManyField(blank=True, to='site_applications.application'),
        ),
    ]
