# Generated by Django 6.0.3 on 2026-04-03 13:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='banners',
            name='description_en',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='banners',
            name='description_ru',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='banners',
            name='description_tk',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='banners',
            name='short_description_en',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='banners',
            name='short_description_ru',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='banners',
            name='short_description_tk',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='banners',
            name='title_en',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='banners',
            name='title_ru',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='banners',
            name='title_tk',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
