# Generated by Django 6.0.3 on 2026-04-03 13:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_banners_description_en_banners_description_ru_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='banners',
            name='description',
        ),
        migrations.RemoveField(
            model_name='banners',
            name='description_en',
        ),
        migrations.RemoveField(
            model_name='banners',
            name='description_ru',
        ),
        migrations.RemoveField(
            model_name='banners',
            name='description_tk',
        ),
    ]
