# Generated by Django 6.0.3 on 2026-04-05 12:40

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Teams',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=100)),
                ('full_name_ru', models.CharField(max_length=100, null=True)),
                ('full_name_en', models.CharField(max_length=100, null=True)),
                ('full_name_tk', models.CharField(max_length=100, null=True)),
                ('job', models.CharField(max_length=100)),
                ('job_ru', models.CharField(max_length=100, null=True)),
                ('job_en', models.CharField(max_length=100, null=True)),
                ('job_tk', models.CharField(max_length=100, null=True)),
                ('phrase', models.TextField()),
                ('phrase_ru', models.TextField(null=True)),
                ('phrase_en', models.TextField(null=True)),
                ('phrase_tk', models.TextField(null=True)),
                ('image', models.ImageField(upload_to='teams/')),
                ('date', models.DateField(auto_now_add=True)),
            ],
        ),
    ]
