# Generated by Django 6.0.3 on 2026-04-05 13:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('team', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='teams',
            options={'ordering': ('-date',), 'verbose_name': 'Команду', 'verbose_name_plural': 'Наша команда'},
        ),
    ]
