# Generated by Django 6.0.3 on 2026-04-18 19:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('site_applications', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='application',
            options={'ordering': ['priority'], 'verbose_name': 'Application', 'verbose_name_plural': 'Applications'},
        ),
        migrations.AddField(
            model_name='application',
            name='description_en',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='application',
            name='description_ru',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='application',
            name='description_tk',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='application',
            name='title_en',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='application',
            name='title_ru',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='application',
            name='title_tk',
            field=models.CharField(max_length=255, null=True),
        ),
    ]
