# Generated by Django 6.0.3 on 2026-04-03 14:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('innovations', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='innovations',
            name='description_en',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='innovations',
            name='description_ru',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='innovations',
            name='description_tk',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='innovations',
            name='name_en',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='innovations',
            name='name_ru',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='innovations',
            name='name_tk',
            field=models.CharField(max_length=200, null=True),
        ),
    ]
