# Generated by Django 6.0.3 on 2026-04-05 11:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('innovations', '0003_innovations_description_en_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='innovations',
            name='product_description_image',
        ),
    ]
