# Generated by Django 6.0.3 on 2026-04-05 11:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('innovations', '0004_remove_innovations_product_description_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='innovations',
            name='product_description_image',
            field=models.ImageField(blank=True, null=True, upload_to='innovations/product_description_image/'),
        ),
    ]
