# Generated by Django 6.0.3 on 2026-04-03 13:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='productcategory',
            options={'verbose_name': 'Категория продукта', 'verbose_name_plural': 'Категории продуктов'},
        ),
        migrations.AlterModelOptions(
            name='productdocumentations',
            options={'verbose_name': 'Документация к продукту', 'verbose_name_plural': 'Документации к продуктам'},
        ),
        migrations.AlterModelOptions(
            name='productgallery',
            options={'verbose_name': 'Галерея продуктов', 'verbose_name_plural': 'Галерея продуктов'},
        ),
        migrations.AlterModelOptions(
            name='products',
            options={'verbose_name': 'Продукт', 'verbose_name_plural': 'Продукты'},
        ),
        migrations.AlterModelOptions(
            name='productsize',
            options={'verbose_name': 'Размер продукта', 'verbose_name_plural': 'Размер продуктов'},
        ),
    ]
