# Generated by Django 6.0.3 on 2026-04-03 14:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0002_alter_productcategory_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='productcategory',
            name='name_en',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='productcategory',
            name='name_ru',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='productcategory',
            name='name_tk',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='productdocumentations',
            name='name_en',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='productdocumentations',
            name='name_ru',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='productdocumentations',
            name='name_tk',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='productgallery',
            name='name_en',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='productgallery',
            name='name_ru',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='productgallery',
            name='name_tk',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='products',
            name='description_en',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='products',
            name='description_ru',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='products',
            name='description_tk',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='products',
            name='name_en',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='products',
            name='name_ru',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='products',
            name='name_tk',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='products',
            name='short_description_en',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='products',
            name='short_description_ru',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='products',
            name='short_description_tk',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='productsize',
            name='name_en',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='productsize',
            name='name_ru',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='productsize',
            name='name_tk',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
