# Generated by Django 6.0.3 on 2026-04-05 11:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0003_productcategory_name_en_productcategory_name_ru_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='products',
            name='product_documentations',
            field=models.ManyToManyField(blank=True, related_name='products_list', to='products.productdocumentations'),
        ),
    ]
