# Generated by Django 6.0.3 on 2026-04-06 16:14

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0005_productsubcategory_products_subcategory'),
    ]

    operations = [
        migrations.AddField(
            model_name='productdocumentations',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='productdocumentations',
            name='description',
            field=models.TextField(blank=True, null=True, verbose_name='Description'),
        ),
        migrations.AddField(
            model_name='productdocumentations',
            name='file_size',
            field=models.IntegerField(blank=True, null=True, verbose_name='File Size (bytes)'),
        ),
        migrations.AddField(
            model_name='productdocumentations',
            name='is_active',
            field=models.BooleanField(default=True, verbose_name='Active'),
        ),
        migrations.AddField(
            model_name='productdocumentations',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
