# Generated by Django 6.0.3 on 2026-04-06 16:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0006_productdocumentations_created_at_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='productdocumentations',
            name='description_en',
            field=models.TextField(blank=True, null=True, verbose_name='Description'),
        ),
        migrations.AddField(
            model_name='productdocumentations',
            name='description_ru',
            field=models.TextField(blank=True, null=True, verbose_name='Description'),
        ),
        migrations.AddField(
            model_name='productdocumentations',
            name='description_tk',
            field=models.TextField(blank=True, null=True, verbose_name='Description'),
        ),
    ]
