# Generated by Django 6.0.3 on 2026-04-17 12:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0007_productdocumentations_description_en_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='productcategory',
            name='priority',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='productsubcategory',
            name='priority',
            field=models.IntegerField(default=0),
        ),
    ]
