# Generated by Django 6.0.3 on 2026-04-18 14:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0008_productcategory_priority_productsubcategory_priority'),
    ]

    operations = [
        migrations.AddField(
            model_name='products',
            name='is_popular',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='productcategory',
            name='priority',
            field=models.IntegerField(default=0, help_text='Чем ниже тем он первым появится'),
        ),
        migrations.AlterField(
            model_name='productsubcategory',
            name='priority',
            field=models.IntegerField(default=0, help_text='Чем ниже тем он первым появится'),
        ),
    ]
