# Generated by Django 6.0.3 on 2026-05-11 10:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('applications', '0001_initial'),
        ('products', '0010_alter_productdocumentations_description_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='products',
            name='applications',
            field=models.ManyToManyField(to='applications.application'),
        ),
    ]
