# Generated by Django 6.0.3 on 2026-05-11 10:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0011_products_applications'),
        ('site_applications', '0002_alter_application_options_application_description_en_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='products',
            name='applications',
            field=models.ManyToManyField(blank=True, to='site_applications.application'),
        ),
    ]
